name: Build multiplatform Docker image

on:
  push:

env:
  IMAGE_NAME: localhost/hello-flask-image:latest
  BASE_IMAGE: python:3.12.3-alpine

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./main_context
          build-contexts: |
            assets=./extra_context
          platforms: linux/amd64,linux/arm64
          push: false
          # ERROR: docker exporter does not currently support exporting manifest lists
          # https://github.com/docker/buildx/issues/59
          # load: true
          cache-to: type=local,dest=./cache
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            APP_PORT=8080

      - name: List images
        shell: bash
        run: |
          echo '## Images:' >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          printf "$(docker images)\n" >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

      - name: List files
        shell: bash
        run: |
          echo '## Files:' >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          printf "$(ls -lh .)\n" >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

      # load doesn't work
      # - name: Inspect image
      #   shell: bash
      #   run: |
      #     echo '## ${{ env.IMAGE_NAME }} Image:' >> "${GITHUB_STEP_SUMMARY}"
      #     echo '```' >> "${GITHUB_STEP_SUMMARY}"
      #     printf "$(docker inspect ${{ env.IMAGE_NAME }})\n" >> "${GITHUB_STEP_SUMMARY}"
      #     echo '```' >> "${GITHUB_STEP_SUMMARY}"

      - name: Store image
        uses: actions/upload-artifact@v4
        with:
          name: image_cache
          compression-level: 9
          path: ./cache/
          overwrite: true
